#!/bin/csh

foreach t ( 1 2 4 8 12 16 20 24 32 )
  foreach n ( 1 10 100 1000 10000 100000 500000 1000000 )
        clang++ -Xpreprocessor -fopenmp -I/usr/local/include -L/usr/local/lib -lomp  montecarlo.cpp -DNUMT=$t -DNUMTRIALS=$n -o montecarlo
    ./montecarlo
  end
end